### ISSUE TITLE
The sample code with "Simplest OAuth2 Walkthrough" didn't work

### ISSUE THREAD

**Issue by zhangkefeng2010** [IdentityServer/IdentityServer3.Samples#107]
I have configuration example code, the server have been running, but the client code can't work, as related to the https. see error message.
Did I miss something important?

System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at Client.Program.GetClientToken() in c:\Users\jeck.zhang\Documents\Visual Studio 2013\Projects\IdentityServer3.Samples-master\source\Simplest OAuth2 Walkthrough\Client\Program.cs:line 33
       at Client.Program.Main(String[] args) in c:\Users\jeck.zhang\Documents\Visual Studio 2013\Projects\IdentityServer3.Samples-master\source\Simplest OAuth2 Walkthrough\Client\Program.cs:line 11
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.Net.Http.HttpRequestException
       HResult=-2146233088
       Message=An error occurred while sending the request.
       Source=mscorlib
       StackTrace:
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Thinktecture.IdentityModel.Client.OAuth2Client.<RequestAsync>d__a.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Client\OAuth2Client.cs:line 277
       InnerException: System.Net.WebException
            HResult=-2146233079
            Message=The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
            Source=System
            StackTrace:
                 at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
                 at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
            InnerException: System.Security.Authentication.AuthenticationException
                 HResult=-2146233087
                 Message=The remote certificate is invalid according to the validation procedure.
                 Source=System
                 StackTrace:
                      at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
                      at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
                      at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
                 InnerException:

**Comment by zhangkefeng2010** [comment]
When i remove Https in Server and Client, they are work.

**Comment by zhangkefeng2010** [comment]
![2015-03-26_151256](https://cloud.githubusercontent.com/assets/7343086/6841827/289e07de-d3cb-11e4-9666-4d44338e3b59.png)

**Comment by leastprivilege** [comment]
The learn to SSL ;)

**Comment by ryanvgates** [comment]
@leastprivilege it would be nice to provide a heads up in the [documentation](https://identityserver.github.io/Documentation/docs/overview/simplestOAuth.html), repository or somewhere else that configuring ssl is required for the example to work. I ran into the same issue.

**Comment by leastprivilege** [comment]
There’s an “edit” link on each page. Feel free to add that.

— 
cheers
Dominick Baier


On 18 Sep 2015 at 22:33:06, Ryan Gates (notifications@github.com) wrote:

@leastprivilege it would be nice to provide a heads up in the documentation, repository or somewhere else that configuring ssl is required for the example to work. I ran into the same issue.
