### ISSUE TITLE
Dependency Owin >= 1.0 could not be resolved

### ISSUE THREAD

**Issue by margagn** [IdentityServer/IdentityServer3.Samples#165]
I am unable to build/execute the "IdentityServerAspNet5" sample. The project "IdentityServerAspNet5" fails to restore the Owin package. I am getting the following error in Visual Studio 2015: 

What am I missing? 

```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\marti\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnx.exe "C:\Users\marti\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll" restore "D:\temp\IdentityServer3.Samples\source\AspNet5Host\src\IdentityServerAspNet5" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility CLR-x86-1.0.0-beta5-12103
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\marti\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnx.exe "C:\Users\marti\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll" restore "D:\temp\IdentityServer3.Samples\source\AspNet5Host\src\IdentityServerAspNet5" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility CLR-x86-1.0.0-beta5-12103
Restoring packages for D:\temp\IdentityServer3.Samples\source\AspNet5Host\src\IdentityServerAspNet5\project.json
  CACHE https://www.nuget.org/api/v2/
Writing lock file D:\temp\IdentityServer3.Samples\source\AspNet5Host\src\IdentityServerAspNet5\project.lock.json
----------
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\marti\.dnx\packages\Owin\1.0\Owin.1.0.nupkg.sha512'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.Framework.PackageManager.Utils.LockFileUtils.CreateLockFileLibrary(LockFileLibrary previousLibrary, IPackagePathResolver resolver, IPackage package, String correctedPackageName)
   at Microsoft.Framework.PackageManager.RestoreCommand.WriteLockFile(LockFile previousLockFile, String projectLockFilePath, Project project, List`1 graphItems, PackageRepository repository, IEnumerable`1 contexts)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass76_0.<<Execute>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<Execute>d__76.MoveNext()
----------
Restore failed
Could not find a part of the path 'C:\Users\marti\.dnx\packages\Owin\1.0\Owin.1.0.nupkg.sha512'.
```

**Comment by TristinDavis** [comment]
Does anyone know what the actual solution to this issue was?  I"m having the same problem. I just upgraded VS 2015 Pro to 1.0.0-rc1 and tried opening the project, but i get:

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\cdavis\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\dnx.exe "C:\Users\cdavis\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "C:\Users\cdavis\Source\Repos\IdentityServer3.Samples\source\AspNet5\src\IdentityServer" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16202
  CACHE https://www.nuget.org/api/v2/
Restoring packages for C:\Users\cdavis\Source\Repos\IdentityServer3.Samples\source\AspNet5\src\IdentityServer\project.json
Writing lock file C:\Users\cdavis\Source\Repos\IdentityServer3.Samples\source\AspNet5\src\IdentityServer\project.lock.json
----------
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\cdavis\.dnx\packages\Owin\1.0.0\Owin.1.0.0.nupkg.sha512'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.Dnx.Tooling.Utils.LockFileUtils.CreateLockFilePackageLibrary(LockFilePackageLibrary previousLibrary, IPackagePathResolver resolver, IPackage package, String correctedPackageName)
   at Microsoft.Dnx.Tooling.RestoreCommand.WriteLockFile(LockFile previousLockFile, String projectLockFilePath, Project project, List`1 graphItems, PackageRepository repository, IProjectResolver projectResolver, IEnumerable`1 contexts)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
Could not find a part of the path 'C:\Users\cdavis\.dnx\packages\Owin\1.0.0\Owin.1.0.0.nupkg.sha512'.
NuGet Config files used:
    C:\Users\cdavis\AppData\Roaming\NuGet\nuget.config
Feeds used:
    https://www.nuget.org/api/v2/
    C:\Program Files (x86)\Microsoft Web Tools\DNU
