### ISSUE TITLE
System.AggregateException - Simplest OAuth2 Walkthrough

### ISSUE THREAD

**Issue by setiseeker** [IdentityServer/IdentityServer3.Samples#166]
Hi
I am getting a System.AggregateException from this line: client.RequestClientCredentialsAsync("api1").Result in the GetClientToken method.

The Inner exception is: {"An error occurred while sending the request."}

Steps i followed:
I downloaded the latest version of the sample source.
Nuget restored all the packages required with no issue.
I start the server application.
When i run the client application this excpetion is thrown when this line is hit: client.RequestClientCredentialsAsync("api1").Result

The version of IdentityServer is 3.2.0.0-build00174
I am running this in VS2015

Is this a configuration issue on my side or a bug i need to report in the main issue tracker?

**Comment by brockallen** [comment]
It's hard to tell, but might be an SSL issue. Any more info (call stack maybe)?

**Comment by setiseeker** [comment]
Hi Brock,

Here is the exception stack trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Client.Program.GetClientToken() in C:\_tmp\IdentityServer3.Samples-master\source\Simplest OAuth2 Walkthrough\Client\Program.cs:line 33
   at Client.Program.Main(String[] args) in C:\_tmp\IdentityServer3.Samples-master\source\Simplest OAuth2 Walkthrough\Client\Program.cs:line 11
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Inner Exception stack trace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.Client.TokenClient.<RequestAsync>d__1.MoveNext() in c:\Dropbox\identity\IdentityModel\IdentityModel\source\IdentityModel.Shared\Client\TokenClient.cs:line 90

I also tried updating to the pre-release version of IdentityServer 3 and got the same error.
I have not setup or configured any certificates.

Let me know if I can supply any other info.

thanks

**Comment by brockallen** [comment]
I can't tell from that, sorry.

**Comment by setiseeker** [comment]
What other info might help?

**Comment by brockallen** [comment]
For that sample there are 3 projects that each need to be run. Perhaps you didn't launch the server and then the client?

**Comment by setiseeker** [comment]
I kicked off the server exe from explorer before i tried running the client in code.
There server shows the following:
![image](https://cloud.githubusercontent.com/assets/1572716/9494294/825a9406-4c05-11e5-9f76-9de0ec559836.png)

**Comment by setiseeker** [comment]
It might be that the Apis was not running when i tested the client & server. I will test now with all three running and let you know shortly.

**Comment by brockallen** [comment]
Ok, then something about connecting to it is failing -- it's some network related issue from the little bit I can tell. DNS not resolving, you have the wrong port maybe, or the SSL cert is not trusted?

Try visiting the server in the browser: https://localhost:44333/permissions and see what that does for you.

**Comment by lyphtec** [comment]
I ran into the same issue and it was due to the SSL cert not being trusted.

To resolve it, just copy (right-click drag) the "localhost" cert used by IIS Express from the Personal store to the Trust Root Cert Authority:

![image](https://cloud.githubusercontent.com/assets/804473/9597503/daf51b30-50c5-11e5-8881-ef0489a1f516.png)

**Comment by setiseeker** [comment]
Thanks brockallan & lyphtec for the help. Sorry for the Tardy Response.

When going to: https://localhost:44333/permissions  I am getting the following in Chrome:  ERR_CONNECTION_RESET

I have moved my Certificates as per the screen shot.

I still get the same exception as before.

All three projects are running when testing these.

**Comment by lyphtec** [comment]
Confirm that your server is running at that address (specifically the `https` part):

```csharp
            using (WebApp.Start<Startup>("https://localhost:44333"))
            {
                Console.WriteLine("server running...");
                Console.ReadLine();
            }
```
You can try changing it to a different port and accessing it directly in Chrome to see if it works. You should see the welcome screen:

![image](https://cloud.githubusercontent.com/assets/804473/9598408/a0798dac-50ce-11e5-9d8e-1502b1511837.png)

Also, I'm not sure why your IdentityServer is version 3.2.0.0-build00174 as the latest should be v2.0.0 as per http://www.nuget.org/packages/IdentityServer3/.  Are you sure you are using the correct NuGet package?

**Comment by setiseeker** [comment]
Thanks Guys.

Changing my Port was the magic to my issue.

What is strange is I used TCPView to check port 44333 and nothing appears bound to the port.

But changing it to 44336 resolved the issue and I am now seeing the landing page.

Thank you all

**Comment by mheyman** [comment]
I had the same issue. For me the problem was a bad certhash in the sslcert list. Fixed it with

`> netsh http add sslcert ipport=0.0.0.0:44333 certhash=<thumbprint without spaces> appid={00112233-4455-6677-8899-AABBCCDDEEFF}`
