### ISSUE TITLE
Unhandled Exception while creating JWT access token

### ISSUE THREAD

**Issue by ryanvgates** [IdentityServer/IdentityServer3.Samples#171]
How can I make sure that the DefultTokenService has the X509Certificate2 to sign the token with?

I am getting the following exception in the identity server log.

>2015-09-24 11:29:03.072 -04:00 [Error] Unhandled exception
System.ArgumentNullException: Value cannot be null.
Parameter name: certificate
   at System.IdentityModel.Tokens.X509SecurityToken..ctor(X509Certificate2 certificate, String id, Boolean clone, Boolean disposable)
   at System.IdentityModel.Tokens.X509SigningCredentials..ctor(X509Certificate2 certificate)
   at IdentityServer3.Core.Services.Default.DefaultTokenSigningService.SignTokenAsync(Token token) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\Default\DefaultTokenSigningService.cs:line 55
   at IdentityServer3.Core.Services.Default.DefaultTokenService.<CreateSecurityTokenAsync>d__c.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\Default\DefaultTokenService.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at IdentityServer3.Core.ResponseHandling.TokenResponseGenerator.<CreateAccessTokenAsync>d__26.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\TokenResponseGenerator.cs:line 206
--- End of stack trace from previous location where exception was thrown ---

I am following the [MvcCodeFlowClientManual Client Sample](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/MvcCodeFlowClientManual). I am using in memory clients, scopes and users like the gist below.

https://gist.github.com/ryanvgates/56236be70249339c64c5

This happens after the user has gotten the authorization code and is requesting the access token with it. That code can be found in the same gist above. Please let me know if you need any additional information.

**Comment by leastprivilege** [comment]
You need to set the SigningCertificate - check the walkthrough.

**Comment by ryanvgates** [comment]
@leastprivilege That did the trick. Thank you for that pointer.

For anyone else that stumbles upon this issue, refer to the code in the [Certificate.cs file of the AspNetIdentity_2fa project](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/AspNetIdentity_2fa/WebHost/IdSvr/Certificate.cs#L23-L44). You will need to include the idsrv3test.pfx or another .pfx file. If you do use this code, make sure that you set the **Build Action** to **Embedded Resource** for your .pfx file.

**Comment by UlyssesAlves** [comment]
@ryanvgates or @leastprivilege Which walkthrough explains this signing certificate configuration? I'm getting this same error even though my certificate appears to be set up correctly.
