### ISSUE TITLE
500 Response code from ASP.NET 5 Hosting Sample

### ISSUE THREAD

**Issue by zorthgo** [IdentityServer/IdentityServer3.Samples#193]
Hi Guys, I am trying out the new ASP.NET 5 Hosting Sample that was just uploaded, and I am having a little bit of a hard time getting it to work. I've cloned the repo on my machine, and when I try to send a request to the Api project from postman, it throws the error below: 
```
Microsoft.AspNet.Server.Kestrel: Error: An unhandled exception was thrown by the application.
System.InvalidOperationException: No SecurityTokenValidator available for token: asdfa;lsf;alsdfj;asdf
   at Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Authentication.AuthenticationHandler`1.<InitializeAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
```

Has anyone come across this issue before and know how to solve it? Thanks!

**Comment by zorthgo** [comment]
The above error message is thrown regardless or whether the token is valid or not.

**Comment by vincez** [comment]
Any updates? I'm running into the same error.

**Comment by bfloydd** [comment]
+1

**Comment by leastprivilege** [comment]
thats a MS bug - fixed in RC2

**Comment by bfloydd** [comment]
So using ASP.NET 5 RC1 with IdentityServer3 is a bust until 	Feb 2016? Temporary workarounds welcome

Roadmap: https://github.com/aspnet/Home/wiki/Roadmap

**Comment by leastprivilege** [comment]
No - it works for me. Take the sample from the samples repo. 

I am just saying that the RC1 MW throws when it cannot validate the token.

**Comment by zorthgo** [comment]
The sample didn't work for me either. I kept getting the "No SecurityTokenValidator available" exception. So I decided to wait until all the bugs get ironed out before I try the sample again. But in the mean time, I wrote a little ApplicationBuilderExtensions for the UseIdentityServerBearerTokenAuthentication().

ApplicationBuilderExtension: 
```
 public static IApplicationBuilder UseIdentityServerBearerTokenAuthentication(this IApplicationBuilder app, IdentityServerBearerTokenAuthenticationOptions options) 
         { 
             app.UseOwin(addToPipeline => 
             { 
                 addToPipeline(next => 
                 { 
                     var builder = new Microsoft.Owin.Builder.AppBuilder(); 
                     builder.Properties["builder.DefaultApp"] = next; 
                     builder.Properties["host.AppName"] = app.ApplicationServices.GetApplicationUniqueIdentifier(); 
                     builder.SetLoggerFactory(new Serilog.Extras.MSOwin.LoggerFactory()); 
                     builder.UseIdentityServerBearerTokenAuthentication(options); 
                      
                     return AppBuilderExtensions.Build<Func<IDictionary<string, object>, Task>>(builder); 
                 }); 
             }); 
 
 
             return app; 
         } 

```
Which then allows you to use it like this:
```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions 
             { 
                 Authority = "...", 
 
 
                 ValidationMode = ValidationMode.ValidationEndpoint, 
 
 
                 RequiredScopes = new[] { "api1" } 
             }); 

```

**Comment by leastprivilege** [comment]
That's wrapped up here:

https://www.nuget.org/packages/IdentityServer3.AccessTokenValidation.Integration.AspNet/

**Comment by zorthgo** [comment]
Awesome!... I'll use this integration package instead. Thanks for the link!... :)

**Comment by stabbylorenzo** [comment]
Hi Friends, I too see this problem of "***No SecurityTokenValidator available for token***" and do not fully understand the suggestions above. I'm using the ASP.NET 5 examples purely and postman to request a token, then adding "Bearer mytoken" to Authorization header, but always see the error. All with postman.

```
Microsoft.AspNet.Hosting.Internal.HostingEngine: Information: Request starting HTTP/1.1 GET http://localhost:55814/identity  
Microsoft.AspNet.Authentication.JwtBearer.JwtBearerMiddleware: Error: Exception occurred while processing message
System.InvalidOperationException: No SecurityTokenValidator available for token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9
   at Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
Microsoft.AspNet.Hosting.Internal.HostingEngine: Information: Request finished in 0ms 500
Microsoft.AspNet.Server.Kestrel: Error: An unhandled exception was thrown by the application.
System.InvalidOperationException: No SecurityTokenValidator available for token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9
   at Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNet.Authentication.AuthenticationHandler`1.<InitializeAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
The thread 0x52a4 has exited with code 0 (0x0).
The thread 0x1e20 has exited with code 0 (0x0).
```


The tokens are valid. jwt.io can decode them.

Any help is appreciated
