### ISSUE TITLE
Exception in AspNet5 sample published to Azure App Services

### ISSUE THREAD

**Issue by Junicus** [IdentityServer/IdentityServer3.Samples#214]
I'm trying the sample for aspnet5 with a replaced certificate.  Locally, it works correctly but when published to Azure app service I get an exception when reading the certificate

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.Cryptography.CryptographicException: The system cannot find the file specified.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromFile(String fileName, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at IRSI.Services.Identity.Startup.Configure(IApplicationBuilder app, IApplicationEnvironment env, ILoggerFactory loggerFactory) in D:\home\site\approot\src\IRSI.Services.Identity\Startup.cs:line 93
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNet.Hosting.Startup.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNet.Hosting.Startup.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNet.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
```
Was hoping someone can shed some light into the problem.

I traced the file path used in startup.cs, generated the same way as the example:
```

            var certFile = env.ApplicationBasePath + $"{System.IO.Path.DirectorySeparatorChar}irsiidentity.pfx";
```
The path generated is D:\home\site\approot\src\IRSI.Services.Identity\irsiidentity.pfx, I checked in Kudu and the file is right where it should be.  Is there something special I need to do to the file, maybe read/write permissions.

Thanks Junicus

**Comment by Junicus** [comment]
I think I found the solution but would like thoughts on it.  I had to change the line where it reads the certificate like so
```
SigningCertificate = new X509Certificate2(certFile, "pass", X509KeyStorageFlags.MachineKeySet)
```
Apparently the IIS app pool in azure doesn't have access to the user store, that is the default location where the certificate is located, the machine store is generic to the machine I guess.

Does this all sound correct?

Thanks Junicus

**Comment by leastprivilege** [comment]
You should really use the certificate store - and not a file on disk.

https://azure.microsoft.com/en-us/blog/using-certificates-in-azure-websites-applications/

**Comment by Junicus** [comment]
Thanks, I will keep that in mind before I go to production, right now I have the site in the free tier for testing and uploading certificates is not an option.  Also, thanks for the link, that will save me time and effort looking for it later.

**Comment by avmp2208** [comment]
Hi @Junicus , I know this is an old issue but right I'm facing the same, could you share your startup file and if possible the method that load the certificate (this is the one I care about) plz???

Thanks
